### ISSUE TITLE
[LinesCounter] Последовательное чтение

### ISSUE THREAD

**Issue by pavel-b-novikov** [TanyaIgnatenko/nsudotnet#2]
Претензий особо нет, однако у вас на каждую прочтенную из файла строку в худшем случае создается несколько других строк

Вы можете написать обработку каждой строки за один проход?

**Comment by TanyaIgnatenko** [comment]
Исправлено.

**Comment by pavel-b-novikov** [comment]
Учитесь писать state-машины (в смысле конечные автоматы). Пригодится.
